// Generated by CoffeeScript 1.6.3
(function() {
  var EventHandlerUndefined, SourcedError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SourcedError = require('./SourcedError');

  EventHandlerUndefined = (function(_super) {
    __extends(EventHandlerUndefined, _super);

    function EventHandlerUndefined() {
      _ref = EventHandlerUndefined.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    EventHandlerUndefined.prototype.setDefaults = function() {
      if (this.message == null) {
        this.message = "Event handler undefined.";
      }
      return EventHandlerUndefined.__super__.setDefaults.call(this);
    };

    return EventHandlerUndefined;

  })(SourcedError);

  module.exports = EventHandlerUndefined;

}).call(this);

/*
//@ sourceMappingURL=EventHandlerUndefined.map
*/
