// Generated by CoffeeScript 1.6.3
(function() {
  var Event;

  module.exports = Event = (function() {
    function Event(props) {
      if (props == null) {
        props = {};
      }
      this.resourceType = props.resourceType;
      this.resourceId = props.resourceId;
      this.resourceVersion = props.resourceVersion;
      this.index = props.index;
      this.type = props.type;
      this.setPayload(props.payload);
      this.setDefaults();
    }

    Event.prototype.setDefaults = function() {
      return this.type != null ? this.type : this.type = this.constructor.name;
    };

    Event.prototype.setPayload = function(payload) {
      return this.payload = this.constructPayload(payload);
    };

    Event.prototype.constructPayload = function(properties) {
      if (properties == null) {
        properties = {};
      }
      return properties;
    };

    return Event;

  })();

}).call(this);

/*
//@ sourceMappingURL=Event.map
*/
