// Generated by CoffeeScript 1.6.3
(function() {
  var Sourced;

  Sourced = exports;

  exports.Event = require('./Event');

  exports.MemoryStorage = require('./MemoryStorage');

  exports.Resource = require('./Resource');

  exports.Revision = require('./Revision');

  exports.RevisionConflict = require('./RevisionConflict');

  exports.RevisionOutOfSequence = require('./RevisionOutOfSequence');

  exports.Schema = require('./Schema');

  exports.Service = require('./Service');

  exports.SourcedError = require('./SourcedError');

  exports.createService = function(config) {
    return new Sourced.Service(config);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
