// Generated by CoffeeScript 1.6.3
(function() {
  var Resource;

  Resource = (function() {
    function Resource(props) {
      if (props == null) {
        props = {};
      }
      this.id = props.id;
      this.version = props.version;
      this.setDefaults();
    }

    Resource.prototype.setDefaults = function() {
      return this.version != null ? this.version : this.version = 0;
    };

    return Resource;

  })();

  module.exports = Resource;

}).call(this);

/*
//@ sourceMappingURL=Resource.map
*/
