// Generated by CoffeeScript 1.6.3
(function() {
  var Revision, RevisionFactory;

  Revision = require('./Revision');

  RevisionFactory = (function() {
    function RevisionFactory() {}

    RevisionFactory.prototype.construct = function(properties) {
      var revision;
      if (properties == null) {
        properties = {};
      }
      revision = new Revision(properties);
      this.decorate(revision);
      return revision;
    };

    RevisionFactory.prototype.generateId = function() {
      return require('uuid').v4();
    };

    RevisionFactory.prototype.decorate = function(revision) {
      if (revision.resourceId == null) {
        revision.resourceId = this.generateId();
      }
      return revision;
    };

    return RevisionFactory;

  })();

  module.exports = RevisionFactory;

}).call(this);

/*
//@ sourceMappingURL=RevisionFactory.map
*/
