// Generated by CoffeeScript 1.6.3
(function() {
  var Event, Revision;

  Event = require('./Event');

  Revision = (function() {
    function Revision(props) {
      if (props == null) {
        props = {};
      }
      this.domain = props.domain;
      this.resourceType = props.resourceType;
      this.resourceId = props.resourceId;
      this.resourceVersion = props.resourceVersion;
      this.events = props.events;
      this.setDefaults();
    }

    Revision.prototype.setDefaults = function() {
      return this.events != null ? this.events : this.events = [];
    };

    Revision.prototype.addEvent = function(event) {
      if (event.domain == null) {
        event.domain = this.domain;
      }
      if (event.resourceType == null) {
        event.resourceType = this.resourceType;
      }
      if (event.resourceId == null) {
        event.resourceId = this.resourceId;
      }
      if (event.resourceVersion == null) {
        event.resourceVersion = this.resourceVersion;
      }
      if (event.index == null) {
        event.index = this.events.length;
      }
      this.events.push(event);
      return event;
    };

    return Revision;

  })();

  module.exports = Revision;

}).call(this);

/*
//@ sourceMappingURL=Revision.map
*/
