// Generated by CoffeeScript 1.6.3
(function() {
  var RevisionOutOfSequence, SourcedError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SourcedError = require('./SourcedError');

  module.exports = RevisionOutOfSequence = (function(_super) {
    __extends(RevisionOutOfSequence, _super);

    function RevisionOutOfSequence() {
      _ref = RevisionOutOfSequence.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RevisionOutOfSequence.prototype.message = 'The revision you are trying to store has a version that is out of sequence.';

    return RevisionOutOfSequence;

  })(SourcedError);

}).call(this);

/*
//@ sourceMappingURL=RevisionOutOfSequence.map
*/
