// Generated by CoffeeScript 1.6.3
(function() {
  var EventFactory, MemoryStorage, Revision, RevisionFactory, Schema, Service;

  MemoryStorage = require('./MemoryStorage');

  Revision = require('./Revision');

  RevisionFactory = require('./RevisionFactory');

  EventFactory = require('./EventFactory');

  Schema = require('./Schema');

  Service = (function() {
    function Service(config) {
      if (config == null) {
        config = {};
      }
      this.storage = config.storage;
      this.schemas = config.schemas;
      this.revisionFactory = config.revisionFactory;
      this.eventFactory = config.eventFactory;
      this.setDefaults();
    }

    Service.prototype.setDefaults = function() {
      if (this.storage == null) {
        this.storage = new MemoryStorage();
      }
      if (this.revisionFactory == null) {
        this.revisionFactory = new RevisionFactory();
      }
      if (this.eventFactory == null) {
        this.eventFactory = new EventFactory();
      }
      return this.schemas != null ? this.schemas : this.schemas = {};
    };

    Service.prototype.createRevision = function(domain, type, uuid, version) {
      if (version == null) {
        version = 0;
      }
      return this.revisionFactory.construct({
        domain: domain,
        resourceType: type,
        resourceId: uuid,
        resourceVersion: version
      });
    };

    Service.prototype.createEvent = function(type, payload) {
      return this.eventFactory.construct(type, {
        payload: payload
      });
    };

    Service.prototype.storeRevision = function(revision, callback) {
      return this.storage.storeRevision(revision, callback);
    };

    Service.prototype.createSchema = function(resourceType) {
      return new Schema({
        resourceType: resourceType
      });
    };

    Service.prototype.registerSchema = function(schema) {
      return this.schemas[schema.resourceType] = schema;
    };

    Service.prototype.isSchemaRegisteredFor = function(type) {
      return this.schemas.hasOwnProperty(type);
    };

    Service.prototype.hydrate = function(domain, type, id, callback) {
      var resource, schema;
      schema = this.schemas[type];
      resource = schema.constructResource(id);
      return this.storage.findRevisions(domain, type, id, function(error, revisions) {
        if (error != null) {
          return callback(error);
        }
        revisions.forEach(function(revision) {
          var version;
          version = revision.resourceVersion + 1;
          resource = schema.setResourceVersion(resource, version);
          return revision.events.forEach(function(event) {
            return resource = schema.applyEvent(resource, event);
          });
        });
        return callback(null, resource);
      });
    };

    return Service;

  })();

  module.exports = Service;

}).call(this);

/*
//@ sourceMappingURL=Service.map
*/
