// Generated by CoffeeScript 1.6.3
(function() {
  var CustomError, SourcedError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CustomError = require('boco-error').CustomError;

  SourcedError = (function(_super) {
    __extends(SourcedError, _super);

    function SourcedError() {
      _ref = SourcedError.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return SourcedError;

  })(CustomError);

  module.exports = SourcedError;

}).call(this);

/*
//@ sourceMappingURL=SourcedError.map
*/
