// Generated by CoffeeScript 1.6.3
(function() {
  var Event;

  module.exports = Event = (function() {
    function Event(props) {
      if (props == null) {
        props = {};
      }
      this.resourceType = props.resourceType;
      this.resourceId = props.resourceId;
      this.resourceVersion = props.resourceVersion;
      this.index = props.index;
      this.type = props.type;
      this.payload = props.payload;
    }

    return Event;

  })();

}).call(this);

/*
//@ sourceMappingURL=Event.map
*/
