// Generated by CoffeeScript 1.6.3
(function() {
  var Resource;

  module.exports = Resource = (function() {
    function Resource(props) {
      if (props == null) {
        props = {};
      }
      this.id = props.id;
      this.version = props.version;
      this.setDefaults();
    }

    Resource.prototype.setDefaults = function() {
      if (this.version == null) {
        return this.version = 0;
      }
    };

    return Resource;

  })();

}).call(this);

/*
//@ sourceMappingURL=Resource.map
*/
