// Generated by CoffeeScript 1.6.3
(function() {
  var Event, Revision;

  Event = require('./Event');

  module.exports = Revision = (function() {
    function Revision(props) {
      if (props == null) {
        props = {};
      }
      this.resourceType = props.resourceType;
      this.resourceId = props.resourceId;
      this.resourceVersion = props.resourceVersion;
      this.events = props.events;
      this.setDefaults();
    }

    Revision.prototype.setDefaults = function() {
      return this.events = [];
    };

    Revision.prototype.addEvent = function(type, payload) {
      var event;
      if (payload == null) {
        payload = {};
      }
      event = new Event({
        resourceType: this.resourceType,
        resourceId: this.resourceId,
        resourceVersion: this.resourceVersion,
        type: type,
        payload: payload,
        index: this.events.length
      });
      this.events.push(event);
      return event;
    };

    return Revision;

  })();

}).call(this);

/*
//@ sourceMappingURL=Revision.map
*/
