// Generated by CoffeeScript 1.6.3
(function() {
  var SourcedError,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = SourcedError = (function(_super) {
    __extends(SourcedError, _super);

    function SourcedError(props) {
      if (props == null) {
        props = {};
      }
      Error.call(this);
      Error.captureStackTrace(this, this.constructor);
      this.name = props.name;
      if (props.message != null) {
        this.message = props.message;
      }
      this.setDefaults();
    }

    SourcedError.prototype.setDefaults = function() {
      if (this.name == null) {
        return this.name = this.constructor.name;
      }
    };

    SourcedError.prototype.message = 'An error has occurred.';

    return SourcedError;

  })(Error);

}).call(this);

/*
//@ sourceMappingURL=SourcedError.map
*/
